name: Contributter

on:
  schedule:
    - cron: "0 16 * * *" # execute at AM 01:00 JST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_SCREEN_NAME: Ningensei848
      MY_LANGUAGE: ja
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
    steps:
      - name: Setup tweet.sh
        run: |
          sudo apt install curl jq nkf openssl -y
          curl -s https://raw.githubusercontent.com/Ningensei848/lifelog/scripts/tweet.sh > tweet.sh
          chmod +x tweet.sh
      - name: Setup contributter.sh
        run: |
          curl -s https://raw.githubusercontent.com/Ningensei848/lifelog/scripts/contributter.sh > contributter.sh
          chmod +x contributter.sh
      - name: Change Name
        run: |
          ./tweet.sh post "$(./contributter.sh ${MY_SCREEN_NAME})"
